In [31]:
import numpy as np
from scipy.sparse.linalg import eigsh, eigs

In [70]:
m = 1000
n = 1000
F = np.random.normal(size=(m,n))
A = F.T @ F

In [71]:
max_eigval, _ = eigsh(A, k=1, which="LM")
print(max_eigval)

[3939.92371653]


In [76]:
tau = 1.2*max_eigval
B = A - tau*np.eye(n)
smallest_eigval, _ = eigsh(B, k=1, which="LM")

In [77]:
smallest_eigval + tau

array([0.0001008])

In [78]:
np.linalg.eigvalsh(A)

array([1.00800946e-04, 1.17055780e-03, 1.27511356e-02, 1.73774745e-02,
       2.60451844e-02, 4.89607203e-02, 8.91368528e-02, 1.26628720e-01,
       1.47492414e-01, 2.24375413e-01, 2.48215238e-01, 2.53651097e-01,
       2.91472956e-01, 3.58677112e-01, 5.83159203e-01, 6.32771240e-01,
       6.79853694e-01, 7.91446468e-01, 9.33087453e-01, 9.99873062e-01,
       1.03370527e+00, 1.20528120e+00, 1.21959222e+00, 1.40324787e+00,
       1.52717227e+00, 1.68923787e+00, 1.91546985e+00, 2.02850154e+00,
       2.10361570e+00, 2.21844844e+00, 2.27355426e+00, 2.63211221e+00,
       2.65454740e+00, 2.99375671e+00, 3.08955602e+00, 3.43308903e+00,
       3.51131041e+00, 3.59505174e+00, 3.88226100e+00, 4.07334266e+00,
       4.29512384e+00, 4.46287377e+00, 4.60624520e+00, 4.74064352e+00,
       5.04541252e+00, 5.21012658e+00, 5.53821666e+00, 5.73541857e+00,
       6.23835003e+00, 6.36823900e+00, 6.74574476e+00, 6.77570207e+00,
       6.85600657e+00, 7.21043802e+00, 7.49739959e+00, 7.70994377e+00,
      

In [79]:
smallest_eigval

array([-4727.90835904])