In [1]:
import numpy as np
import matplotlib.pyplot as plt

import jlinops

# Check pseudoinverse?

In [7]:
m, n = 4, 10
R = jlinops.build_2d_first_order_derivative( (m, n), boundary="zero" )

In [8]:
Rpseudo = jlinops.SparseCholeskyApproximatePseudoInverseOperator(R)

/Users/jonathanlindbloom/opt/miniconda3/envs/speckle38/lib/python3.8/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


In [9]:
Rpseudo.shape

(40, 80)

In [10]:
z = np.random.normal(size=80)

In [11]:
Rpseudo @ z

array([-0.63045612, -0.39842763,  1.09846508,  0.49998213, -1.10139888,
       -1.41719105, -0.95610318,  0.37289283, -0.53631932, -1.79836677,
       -1.42440921, -0.79940442, -0.1455499 , -0.57198892, -1.63907383,
       -1.7566131 , -1.14159697, -1.08505015, -1.02792095, -0.43053251,
       -1.02571507, -0.65320237, -1.86203423, -2.19030562, -1.4662002 ,
       -0.17988352, -1.29512173, -1.147966  , -0.93314001, -0.57634837,
       -0.88708466, -0.75650909, -0.78779692, -0.89332448, -1.6224558 ,
       -1.34611326, -1.31025843, -1.13440965, -1.44902187, -1.12114698])

In [15]:
np.linalg.pinv(R.A.toarray()) @ z

array([-0.63151345, -0.40000501,  1.0970013 ,  0.49843083, -1.10342032,
       -1.42058104, -0.95992812,  0.36920276, -0.53885639, -1.80308579,
       -1.430209  , -0.80547131, -0.14842139, -0.57733977, -1.64623772,
       -1.76452449, -1.14504947, -1.09112718, -1.0358754 , -0.43927931,
       -1.02943495, -0.65966763, -1.8708364 , -2.20024964, -1.47013624,
       -0.18649228, -1.30410465, -1.15805879, -0.93708933, -0.58321931,
       -0.89621747, -0.76671255, -0.7918541 , -0.900541  , -1.63204265,
       -1.35674153, -1.3145335 , -1.14186743, -1.45876921, -1.13189535])

In [17]:
R.shape

(80, 40)

In [18]:
W = np.random.normal(size=(40,3))

In [21]:
Rpseudo = jlinops.QRPseudoInverseOperator( jlinops.MatrixOperator(R @ W) )

In [23]:
Rpseudo @ z

array([ 0.0722201 ,  0.1037814 , -0.04314348])

In [26]:
np.linalg.pinv( R.A.toarray() @ W ) @ z

array([ 0.0722201 ,  0.1037814 , -0.04314348])